### ISSUE TITLE
タスク一覧

### ISSUE THREAD

**Issue by sayako21** [teritamas/innovation-support-frontend#8]
# 優先度高
## 全体
- [ ] 項目、文言見直し
- [ ] 投票、提案作成時にエラー画面の表示

## ヘッダー
- [x] 「～さん」の表示直す

## 提案画面（/proposal）
- [x] #55
- [x] #9
- [x] #10
- [x] #54
- [x] #31
- [ ] タグの付与
- [x] #78

## 詳細画面（/proposal/:proposal_id）

- [ ] 投票したユーザのアイコンを、個別に表示する
- [x] #74
- [ ] 提案の種類（提案・テスター・アンケート）表示する
- [x] 目標金額、その他を表示
- [x] #34
- [x] #33
- [x] 賛否のCSS抜けているの直す
- [x] 賛否の理由が概要とつながっているの修正
- [x] #11
- [x] #12
- [x] #90

# 優先度中
## 全体
- [x] #36

## 一覧画面（/lists）
- [x] #45
- [x] #42
- [x] #82

## マイページ（/mypage）
- [x] 獲得したトークン表示
- [x] #17
- [x] #32

## ギフト（/gift）
- [x] #35
- [x] #30
- [x] #40
- [x] #41
- [x] #89
- [x] #88

## タイムラインの画面作成
-  [x] タイムラインのBEと繋ぎこみ
- [ ] レイアウト作成

# 優先度低
## 全体
- [x] #71
- [ ] テスター、アンケート画面で項目変える

## ログイン
- [x] #93
- [x] #83

## 提案画面（/proposal）
- [x] レスポンシブ
- [x] #63

## ホーム（/）
- [x] 何を表示する
  - [x] #13
  - [x] 実装
→ホーム画面には投票や提案のタイムラインを表示することに決定。 `タイムライン画面作成`で実装する

**Comment by sey323** [comment]
ハッカソン終了のためクローズ
